version: "3.9"

services:
  server:
    container_name: ngcash-server
    build: ./server
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - ./server:/server
      - server_node_modules:/server/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - database

  database:
    container_name: ngcash-database
    image: postgres:15-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  database:
  server_node_modules:
